# Generated by Django 5.2.15 on 2026-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='e.g. Maruti Suzuki, Hyundai, Toyota', max_length=80)),
                ('car_name', models.CharField(help_text='e.g. Swift, Creta, Innova Crysta', max_length=100)),
                ('model', models.CharField(help_text='e.g. 2023, VXi, ZX', max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('cng', 'CNG'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('mileage', models.CharField(help_text='e.g. 18 km/l or 220 km/charge', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide this car from bookings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
