# Generated by Django 5.2.15 on 2026-06-29 17:17

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('driving_license', models.ImageField(upload_to=bookings.models.license_upload_path)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note, e.g. reason for rejection.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
